#!/usr/bin/ruby
# Ruby front-end for your compiler.
# You are free to change the language used for this script,
# but do *not* change its name.

targetPath = ARGV[0]

# puts `sbt "run-main Main #{targetPath}"`

`sbt "run-main Main #{targetPath}"`

puts `echo $?`
