#!/usr/bin/ruby

dir = ARGV[0]

files = `find #{dir}/ -name *.wacc`.split("\n")

def count
  @count ||= -1
  @count += 1
end

def getString(file)
  return `./compile #{file}`
end

# def getError(msg)
#   return !(msg.include? "success")
# end
def getError(msg)
  return !(msg.include? "Nonzero exit code returned from runner: 100")
end

def fullMessage(file)
  if getError(getString(file))
    puts "#{file} returns error code: #{getString(file)} #{Time.new.inspect}\n\n"
    count
  end
  # return ""
end

files.map { |file| fullMessage(file) }

puts "There are #{count} errors in #{dir}"
