#!/usr/bin/ruby

dir = ARGV[0]

files = `find #{dir} -name *.wacc`.split("\n")

def removePath(file)
  return file[file.rindex('/') + 1, file.rindex('.')]
end

def count
  @count ||= -1
  @count += 1
end

def outputMessage(file)
  puts "#{file}"
  system("./compile2 #{file}")
  `arm-linux-gnueabi-gcc -o #{removePath(file)} -mcpu=arm1176jzf-s #{removePath(file)}.s`
  # emulator
  puts "\n\n"
end

initTime = Time.now

files.map { |file| outputMessage(file)  }

puts "There are #{count}/#{files.length} errors in #{dir}"

puts "Time taken to run compile on all files: #{Time.now - initTime}"
