#!/usr/bin/ruby

dir = ARGV[0]

files = `find #{dir} -name *.wacc`.split("\n")

def removePath(file)
  file = file[file.rindex('/') + 1, file.size]
  return file[0..file.size - 6]
end

def count
  @count ||= -1
  @count += 1
end

def outputMessage(file)
  puts "#{file}\n\n"
  puts terminalOutput = `./compile2 #{file}`
  `arm-linux-gnueabi-gcc -o #{removePath(file)} -mcpu=arm1176jzf-s #{removePath(file)}.s`
  puts system("qemu-arm -L /usr/arm-linux-gnueabi/ #{removePath(file)}")
  # change system so we get the exit code
  puts "\n\n"
end

initTime = Time.now

files.map { |file| outputMessage(file)  }

puts "There are #{count}/#{files.length} errors in #{dir}"

puts "Time taken to run compile on all files: #{Time.now - initTime}"
