#!/usr/bin/ruby

dir = "wacc_examples/valid"

files = `find #{dir}/ -name *.wacc`.split("\n")

def getString(file)
  return `./compile #{file}`
end

def getError(msg)
  return !(msg.include? "success")
end

def fullMessage(file)
  if getError(getString(file))
    puts "#{file} returns error code: #{getString(file)} #{Time.new.inspect}\n\n"
  end
  # return ""
end

files.map { |file| fullMessage(file) }

